# Generated by Django 2.1.1 on 2018-09-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pontoturistico_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontoturistico',
            old_name='atracao',
            new_name='atracoes',
        ),
    ]
